In [491]:
import numpy as np
from sklearn.model_selection import train_test_split
import csv

In [585]:
class ELM_model:
    
    def __init__(self,data,labels):
        self.data = data.copy()
        self.labels = labels.copy()
        self.DataRange = self.obtainRange(self.data)
        self.normalizeData(self.data)
        self.LabelsRange = self.obtainRange(self.labels)
        self.normalizeLabels(self.labels)        
        self.model_created=False    
    
    def obtainRange(self, A): #obtain a list of  lowest and highest entries for all comuns
        _,m = A.shape
        L=[(min(A[:,i:i+1]), max(A[:,i:i+1])) for i in range(m)]
        return(L)
    
    def normalizeData(self,A):
        self.__normalizeEntries(A,self.DataRange)
    
    def normalizeLabels(self,A):
        self.__normalizeEntries(A,self.LabelsRange)
        
    def __normalizeEntries(self,A,Range):
        _,m=A.shape
        for i in range(m):
            min_value, max_value = Range[i]
            A[:,i:i+1]=(A[:,i:i+1]-min_value)/(max_value-min_value)            

            
            
    def CreateModel(self,neurons,activation):
        N, n = self.data.shape
        W=CreateRandomMatrix(n,neurons)
        b=CreateRandomMatrix(1,neurons)
        try:
            A=X*W+b
            H=activation(A)
        except:
            print("Error: Building H: shape of matrices W,X,b are incomparable.\n X:",X.shape,"\n W:",W.shape,"\n b:",b.shape)
            return()        
        self.beta=MoorePenrose(H)*T
        self.W=W
        self.b=b
        self.activation=activation
        self.model_created=True
        print("Model created.")

    def predict(self,x):
        if(self.model_created):
            return(self.activation(x*self.W+self.b)*self.beta)           
        else:
            print("Model has not been created yet!")

    def MoorePenrose(self,A):
        _,m=np.shape(A)
        B=(A.transpose())*A
        try:        
            C=np.linalg.inv(B)               
        except:
            print("Error: columns of matrix are not linearly independent!")
            print("Matrix A\n",A)
            C=np.zeros((m,m))
        return(C*(A.transpose()))


    def ReLu(self,x):
        return(max(x,0))

    def sigmoid(self,z):
        return 1/(1 + np.exp(-z))

    def CreateRandomMatrix(self,N,Nt,center=0.5,scale=1):
        A=np.random.rand(N,Nt)
        return(np.matrix((A-center)*scale))
   
    def denormalize(self):
        data=self.data.copy()
        self.denormalize(data,self.MinMax_data)
        labels=self.labels.copy()
        self.denormalize(labels,self.MinMax_labels)
        return((data,labels))
    
    def __denormalize(self,A,MinMax):        
        _,m = A.shape        
        for i in range(m):
            L=A[:,i:i+1]
            min_value, max_value = MinMax[i]            
            A[:,i:i+1] = L*(max_value-min_value)+min_value        
        return(A)

In [586]:
dataframe = np.loadtxt("modeldata.csv",delimiter=",")

dataframe=dataframe[:100]

data = dataframe[:,:9]
labels= dataframe[:,9:]

data_train, data_test, labels_train, labels_test = train_test_split(data, labels, test_size=0.20, random_state=42)


In [587]:
model=ELM_model(data_train,labels_train)

In [591]:
model.CreateModel(10,sigmoid)

Model created.


C:\Users\lomp\AppData\Local\Temp\ipykernel_8340\3749121611.py:27: RuntimeWarning: overflow encountered in exp
  return 1/(1 + np.exp(-z))


In [592]:
model.normalizeData(data_test)


In [593]:
model.normalizeLabels(labels_test)

In [596]:
model.predict(data_test)-labels_test

C:\Users\lomp\AppData\Local\Temp\ipykernel_8340\3749121611.py:27: RuntimeWarning: overflow encountered in exp
  return 1/(1 + np.exp(-z))


matrix([[ 0.51110856,  0.1749207 , -0.06931487,  0.05704327,  0.33183041,
         -0.71668028,  0.30557296],
        [-1.13267742, -0.27089416, -0.4165087 ,  0.2124858 ,  0.36967822,
          0.40894246, -0.54134973],
        [ 0.59389672,  0.61919273, -0.07682562, -0.26336432, -0.23167996,
          0.32233473, -0.45322298],
        [-0.312321  ,  0.31672149, -0.48931488,  0.2411232 , -0.46082893,
          0.94662923,  0.02024641],
        [-0.57343952, -0.42851399, -0.26928974, -0.12133197, -0.53001679,
         -0.41441094,  0.27876369],
        [-1.5179408 , -0.89233553,  0.17282454,  0.33076981,  0.38026802,
          0.36823167, -0.95651153],
        [ 0.50854965,  0.74585141, -0.49995553, -0.12337619,  0.35286576,
         -0.4806087 ,  0.57869864],
        [-0.76751328,  0.07409273,  0.06129438, -0.39236432, -0.29002995,
          0.47299473,  0.15181702],
        [-1.055281  , -0.3487785 , -0.15991488, -0.2206368 , -0.66795894,
          0.12025224,  0.07457341],
        [ 

In [539]:
W[0,1]=78
W[1,2]=-1

In [545]:
[(min(W[:,i:i+1]), max(W[:,i:i+1])) for i in range(3)]

[(matrix([[0.]]), matrix([[1.]])),
 (matrix([[0.5]]), matrix([[78.]])),
 (matrix([[-1.]]), matrix([[1.]]))]

In [65]:
H

array([[9., 2., 0.],
       [0., 3., 1.]])

In [66]:
np.tanh(H)

array([[0.99999997, 0.96402758, 0.        ],
       [0.        , 0.99505475, 0.76159416]])

In [417]:
model=ELModel(dataframe)

In [418]:
model.denormalize()

array([[ 1.2636   , -0.040305 , -0.21906  , ...,  0.55241  ,  0.13507  ,
         0.23804  ],
       [ 1.4146   ,  0.66479  , -0.52256  , ...,  0.59662  , -0.7609   ,
        -0.033924 ],
       [ 0.12329  ,  0.59014  , -0.37037  , ...,  0.83704  ,  0.25389  ,
        -0.4062   ],
       ...,
       [ 1.4064   , -0.1268   , -0.041386 , ...,  0.0068805,  0.13012  ,
         0.12539  ],
       [ 0.68215  ,  0.037748 , -0.45814  , ...,  0.71761  , -0.51773  ,
         0.064303 ],
       [ 0.69097  ,  0.46172  , -0.48339  , ..., -0.68968  ,  0.19071  ,
        -0.66527  ]])

In [419]:
model.dataframe

array([[0.81485838, 0.15379722, 0.4361946 , ..., 0.77654536, 0.56751874,
        0.61948114],
       [0.9059512 , 0.96194755, 0.00141822, ..., 0.79870387, 0.11914365,
        0.48306397],
       [0.1269508 , 0.87638685, 0.21943672, ..., 0.91920488, 0.62698047,
        0.29633029],
       ...,
       [0.90100443, 0.05466028, 0.69072   , ..., 0.50312029, 0.56504159,
        0.56297589],
       [0.46409073, 0.2432583 , 0.09370255, ..., 0.85934532, 0.24083453,
        0.53233465],
       [0.46941152, 0.72919723, 0.05753087, ..., 0.1539969 , 0.59536297,
        0.16638075]])